---
# tasks file for nginx
- name: install apt-transport-https
  apt: name=apt-transport-https update_cache=yes
  become: yes

- name: install packages
  apt: name={{ item }} update_cache=yes force=yes
  with_items:
    - nginx
    - curl
  become: yes
  notify:
    - restart nginx
